name: "ukraine-private-sector-donations-tracker"
fallback_dir: "fallback_data"

outputs:
  transactions:
    headers:
      - "Month"
      - "Reporting org id"
      - "Reporting org name"
      - "Reporting org type"
      - "Sector"
      - "Recipient country"
      - "Humanitarian?"
      - "Strict?"
      - "Transaction type"
      - "Activity id"
      - "Net money"
      - "Total money"
    hxltags:
      - "#date+month"
      - "#org+id"
      - "#org+name"
      - "#org+type"
      - "#sector"
      - "#country"
      - "#indicator+bool+humanitarian"
      - "#indicator+bool+strict"
      - "#x_transaction_type"
      - "#activity+code"
      - "#value+net"
      - "#value+total"
    csv:
      filename: "transactions.csv"
    json:
      filename: "transactions.json"
      hxltags:
        - "#date+month"
        - "#org+id"
        - "#org+type"
        - "#sector"
        - "#country"
        - "#indicator+bool+humanitarian"
        - "#indicator+bool+strict"
        - "#x_transaction_type"
        - "#activity+code"
        - "#value+net"
        - "#value+total"
  flows:
    headers:
      - "Reporting org id"
      - "Reporting org name"
      - "Reporting org type"
      - "Provider org id"
      - "Provider org name"
      - "Provider org type"
      - "Receiver org id"
      - "Receiver org name"
      - "Receiver org type"
      - "Humanitarian?"
      - "Strict?"
      - "Transaction direction"
      - "Total money"
    hxltags:
      - "#org+id+reporting"
      - "#org+name+reporting"
      - "#org+reporting+type"
      - "#org+id+provider"
      - "#org+name+provider"
      - "#org+type+provider"
      - "#org+id+receiver"
      - "#org+name+receiver"
      - "#org+type+receiver"
      - "#indicator+bool+humanitarian"
      - "#indicator+bool+strict"
      - "#x_transaction_direction"
      - "#value+total"
    csv:
      filename: "flows.csv"
    json:
      filename: "flows.json"
      hxltags:
        - "#org+id+reporting"
        - "#org+reporting+type"
        - "#org+name+provider"
        - "#org+name+receiver"
        - "#indicator+bool+humanitarian"
        - "#indicator+bool+strict"
        - "#x_transaction_direction"
        - "#value+total"
  orgs:
    headers:
      - "Reporting org id"
      - "Reporting org name"
    hxltags:
      - "#org+id+reporting"
      - "#org+name+reporting"
    csv:
      filename: "reporting_orgs.csv"
    json:
      filename: "reporting_orgs.json"

