dataset_ukraine: "ukraine-private-sector-donations-tracker"
dataset_turkey: "turkiye-syria-earthquake-private-sector-donations-tracker"
fallback_dir: "fallback_data"

outputs:
  transactions:
    input:
      headers:
        - "Month"
        - "Reporting org id"
        - "Reporting org name"
        - "Reporting org type"
        - "Sector"
        - "Receiver org id"
        - "Receiver org name"
        - "Humanitarian?"
        - "Strict?"
        - "Transaction type"
        - "Activity id"
        - "Net money"
        - "Total money"
        - "Notes"
      hxltags:
        - "#date+month"
        - "#org+id"
        - "#org+name"
        - "#org+type"
        - "#sector"
        - "#org+id+receiver"
        - "#org+name+receiver"
        - "#indicator+bool+humanitarian"
        - "#indicator+bool+strict"
        - "#x_transaction_type"
        - "#activity+code"
        - "#value+net"
        - "#value+total"
        - "#description"
    output:
      csv:
        filename: "transactions.csv"
      json:
        filename: "transactions.json"
        metadata:
          "#date+run": "{{today}}"
          "#meta+transactions+num": "{{num_transactions}}"
        hxltags:
          - "#date+month"
          - "#org+id"
          - "#org+name"
          - "#org+type"
          - "#sector"
          - "#org+id+receiver"
          - "#org+name+receiver"
          - "#indicator+bool+humanitarian"
          - "#indicator+bool+strict"
          - "#x_transaction_type"
          - "#activity+code"
          - "#value+net"
          - "#value+total"
          - "#description"
  flows:
    input:
      headers:
        - "Reporting org id"
        - "Reporting org name"
        - "Reporting org type"
        - "Provider org id"
        - "Provider org name"
        - "Provider org type"
        - "Receiver org id"
        - "Receiver org name"
        - "Receiver org type"
        - "Humanitarian?"
        - "Strict?"
        - "Transaction direction"
        - "Total money"
        - "Notes"
      hxltags:
        - "#org+id+reporting"
        - "#org+name+reporting"
        - "#org+reporting+type"
        - "#org+id+provider"
        - "#org+name+provider"
        - "#org+type+provider"
        - "#org+id+receiver"
        - "#org+name+receiver"
        - "#org+type+receiver"
        - "#indicator+bool+humanitarian"
        - "#indicator+bool+strict"
        - "#x_transaction_direction"
        - "#value+total"
        - "#description"
    output:
      csv:
        filename: "flows.csv"
      json:
        filename: "flows.json"
        metadata:
          "#date+run": "{{today}}"
          "#meta+flows+num": "{{num_flows}}"
        hxltags:
          - "#org+id+reporting"
          - "#org+name+reporting"
          - "#org+reporting+type"
          - "#org+id+provider"
          - "#org+name+provider"
          - "#org+type+provider"
          - "#org+id+receiver"
          - "#org+name+receiver"
          - "#org+type+receiver"
          - "#indicator+bool+humanitarian"
          - "#indicator+bool+strict"
          - "#x_transaction_direction"
          - "#value+total"
          - "#description"
  reporting_orgs:
    input:
      headers:
        - "Reporting org id"
        - "Reporting org name"
      hxltags:
        - "#org+id+reporting"
        - "#org+name+reporting"
    output:
      csv:
        filename: "reporting_orgs.csv"
      json:
        filename: "reporting_orgs.json"
        metadata:
          "#date+run": "{{today}}"
          "#meta+reporting_orgs+num": "{{num_reporting_orgs}}"
  receiver_orgs:
    input:
      headers:
        - "Receiver org id"
        - "Receiver org name"
      hxltags:
        - "#org+id+receiver"
        - "#org+name+receiver"
    output:
      csv:
        filename: "receiver_orgs.csv"
      json:
        filename: "receiver_orgs.json"
        metadata:
          "#date+run": "{{today}}"
          "#meta+receiver_orgs+num": "{{num_receiver_orgs}}"

